(#97) Cria documento do RoadMap
fga-eps-mds/2022-1-PUMA-Doc pull request #104
Opened 2022-07-23 00:59 UTC by enzoggqs

Co-authored-by: YuriBre <brenoyuri5000@gmail.com>
Co-authored-by: GabriellCabrall <gabrielbielcabral@gmail.com>

## Descrição
Cria documento de Roadmap

## Issue

Closes #97 

## Principais Implementações

Criação do documento do Roadmap

## Tipos de Mudanças
 - [ ] Bug fix (alteração que corrige uma issue e não altera funcionalidades já existentes);
 - [ ] Nova feature (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
 - [ ] Alteração disruptiva (Breaking change) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
 - [x] Documentação

2022-07-23 12:34 UTC, giovannabbottino commented
Nosso Roadmap não é no zenhub? Além disso, referência de outros grupos de mds-eps de outros temas não são referência

2022-07-23 12:51 UTC, enzoggqs commented
> Nosso Roadmap não é no zenhub? Além disso, referência de outros grupos de mds-eps de outros temas não são referência

Ficou acordado de fazermos um doc do Roadmap tb. E fizemos ele com base no zenhub e nas issues já feitas. E sobre a referência vou corrigir aqui

2022-07-25 02:11 UTC, Bruno-Felix reviewed
Show!! 

Só a visualização do iframe me chamou a atenção.

2022-07-25 02:11 UTC, Bruno-Felix commented on docs/projeto/roadmap.md
> +<iframe width="700" height="300" style="-webkit-transform:scale(0.8);-moz-transform-scale(0.8);" frameborder="0" scrolling="yes" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSQmpkGOKgmA7R4bm
Acredito estar pequeno o iframe.

width="1000" height="600" me parece um pouco melhor de se visualizar.

2022-07-25 02:29 UTC, YuriBre commented on docs/projeto/roadmap.md
> +<iframe width="700" height="300" style="-webkit-transform:scale(0.8);-moz-transform-scale(0.8);" frameborder="0" scrolling="yes" src="https://docs.google.com/spreadsheets/d/e/2PACX-1vSQmpkGOKgmA7R4bm
Mudei o tamanho conforme a sugestão

2022-07-25 02:35 UTC, Bruno-Felix approved these changes
Boa!!

2022-07-26 20:51 UTC, santosm46 requested changes

2022-07-29 12:37 UTC, santosm46 approved these changes

2022-07-29 13:17 UTC, merged