[#64] Desenvolver documento de EAP
fga-eps-mds/2022-1-PUMA-Doc pull request #105
Opened 2022-07-25 01:50 UTC by YuriBre

[#64] Desenvolver documento de EAP

## Descrição
Desenvolvendo documento de EAP, estruturando tudo que foi feito e deve ser feito no projeto.

## Issue
Closes #64

## Tipos de Mudanças
 - [ ] Bug fix (alteração que corrige uma issue e não altera funcionalidades já existentes);
 - [ ] Nova feature (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
 - [ ] Alteração disruptiva (Breaking change) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
 - [x] Documentação

2022-07-25 12:58 UTC, giovannabbottino requested changes
Ta faltando a âncora da referência

No local que você precisa referenciar no texto.
```[[1]](#ref1).```

Na referência
```<a id="ref1"></a>
[1] REFERENCIA, Bla (2022) Disponivel em Bla. Acesso em Bla```

2022-07-25 21:27 UTC, YuriBre commented
Arrumei a referência.

2022-07-25 22:08 UTC, giovannabbottino approved these changes

2022-07-28 13:51 UTC, enzoggqs approved these changes

2022-07-28 13:51 UTC, merged