(#110) Documentando Review e Retrospective Sprint 5
fga-eps-mds/2022-1-PUMA-Doc pull request #111
Opened 2022-07-31 19:42 UTC by Bruno-Felix

## Descrição
PR destinado a documentação da Planning da Sprint 6 e da Review da Sprint 5

## Issue

Closes #110

## Tipos de Mudanças
 - [ ] Bug fix (alteração que corrige uma issue e não altera funcionalidades já existentes);
 - [ ] Nova feature (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
 - [ ] Alteração disruptiva (Breaking change) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
 - [x] Documentação

2022-07-31 22:52 UTC, enzoggqs approved these changes

2022-08-01 01:17 UTC, codehg requested changes
Revisar 'sprints' por favor

2022-08-01 01:17 UTC, codehg commented on docs/sprints/sprint5/review.md
> +# Review Sprint 5
Corrigir 'Sprint', ainda estamos em 'semanas'

2022-08-01 01:17 UTC, codehg commented on docs/sprints/sprint6/planning.md
> +# Planejamento Sprint 6
Corrigir 'Sprint', ainda estamos em 'semanas'

2022-08-01 01:21 UTC, Bruno-Felix commented on docs/sprints/sprint5/review.md
> +# Review Sprint 5
Será resolvido no pr [112](https://github.com/fga-eps-mds/2022-1-PUMA-Doc/pull/112)

2022-08-01 01:21 UTC, Bruno-Felix commented on docs/sprints/sprint6/planning.md
> +# Planejamento Sprint 6
Será resolvido no pr [112](https://github.com/fga-eps-mds/2022-1-PUMA-Doc/pull/112)

2022-08-01 01:23 UTC, codehg approved these changes
Correto

2022-08-01 01:25 UTC, merged