Plano de contribuição
fga-eps-mds/2022-1-PUMA-Doc pull request #47
Opened 2022-07-11 00:19 UTC by bhsouza

[#34] Plano de contribuição

## Descrição

Cria documento com instruções de contribuição no projeto.

## Issue

Closes #34 

## Tipos de Mudanças
 - [ ] Documentação

2022-07-11 16:13 UTC, Bruno-Felix commented
[Corrige bug visual](https://github.com/fga-eps-mds/2022-1-PUMA-Doc/pull/47/commits/4df04f3ec03c135b740f4be10f6ed020496d0a45)

[Remove crases](https://github.com/fga-eps-mds/2022-1-PUMA-Doc/pull/47/commits/ef787aa2f996d852e85f56eb39bd2635a16fabe4)

Commits usando as politicas, por favor. Sprint 3 já.

2022-07-11 20:28 UTC, enzoggqs requested changes
Falta adicionar a rota para o documento no arquivo mkdocs.yml

2022-07-13 13:48 UTC, enzoggqs requested changes
Tudo certo! Só uma pequena correção: acredito que para seguir o padrão dos demais documentos já criados, seria melhor botar o histórico de versão no começo e não no final no arquivo

2022-07-13 16:40 UTC, giovannabbottino approved these changes

2022-07-14 12:00 UTC, merged