WIP Doc/arquitetura
fga-eps-mds/2022-1-PUMA-Doc pull request #55
Opened 2022-07-12 23:05 UTC by edudsan

## Descrição

## Issue

## Principais Implementações

## Tipos de Mudanças
 - [ ] Bug fix (alteração que corrige uma issue e não altera funcionalidades já existentes);
 - [ ] Nova feature (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
 - [ ] Alteração disruptiva (Breaking change) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
 - [ ] Documentação

2022-07-23 16:40 UTC, Bruno-Felix commented on docs/produto/doc_arquitetura.md
> +### Representação dos Serviços
Não deveríamos explicar todos os Serviços da imagem?

Se Explicamos a maioria, Alocate e DataBase também deveria ser explicado.

2022-07-23 16:42 UTC, Bruno-Felix commented on docs/produto/doc_arquitetura.md
> +| SB    | ENUM | Utilizado quando a proposta é submetida.                                           |
Não entendi a coluna "ENUM".

Deveria ter uma explicação?!
Não encontrei nenhum local do documento que linka com esse tipo ENUM.

2022-07-23 16:43 UTC, Bruno-Felix commented on docs/produto/doc_arquitetura.md
> +##### Relacionamentos
A visualização desse Tópico não ficou legal de se ler.

2022-07-23 16:45 UTC, Bruno-Felix commented on README.md
> +**Código da Disciplina:** FGA0138
Não entendi o motivo de alterar o README no documento de arquitetura.

2022-07-23 16:45 UTC, Bruno-Felix reviewed
Alguns pontos levantados sobre o documento.

78 commits para desenvolver um documento?

2022-07-24 17:13 UTC, enzoggqs commented on docs/produto/doc_arquitetura.md
> +| AD    | ENUM | Para os semestres eu estão em andamento. |
Corrigir "Para os semestres eu estão em andamento"

2022-07-24 17:14 UTC, enzoggqs commented on docs/produto/doc_arquitetura.md
> +| EC    | ENUM | Utilizado quando o desenvolvimento do proejto for concluído.                       |
corrigir a palavra "proejto

2022-07-24 17:16 UTC, enzoggqs requested changes
Fazer correções solicitadas

2022-07-25 01:26 UTC, enzoggqs approved these changes

2022-07-25 13:58 UTC, santosm46 approved these changes

2022-07-25 13:58 UTC, merged