[#60] Adiciona o documento de Metodologia
fga-eps-mds/2022-1-PUMA-Doc pull request #90
Opened 2022-07-17 22:03 UTC by GabriellCabrall

## Descrição
Adiciona o documento de metodologia

## Issue

Closes #60 

## Principais Implementações

## Tipos de Mudanças
 - [ ] Bug fix (alteração que corrige uma issue e não altera funcionalidades já existentes);
 - [ ] Nova feature (alteração que adiciona uma funcionalidade e não altera funcionalidades já existentes);
 - [ ] Alteração disruptiva (Breaking change) (Correção ou funcionalidade que causa alteração nas funcionalidades existentes);
 - [x] Documentação

2022-07-17 22:09 UTC, giovannabbottino requested changes

2022-07-17 22:09 UTC, giovannabbottino commented on docs/projeto/metodologia.md
> +## Referências
Falta a âncora.

2022-07-17 22:25 UTC, giovannabbottino approved these changes

2022-07-18 01:00 UTC, Bruno-Felix approved these changes
Uhuuu!!

2022-07-18 01:01 UTC, merged